# Generated by Django 4.2.5 on 2023-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_employer"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("upload_resume", models.FileField(upload_to="resumes/")),
                ("degree", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description_1", models.TextField()),
                ("job_title", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("job_start_date", models.DateField()),
                ("job_end_date", models.DateField()),
                ("description_2", models.TextField()),
                ("skill_set", models.TextField()),
            ],
        ),
    ]
