# Generated by Django 4.2.5 on 2023-09-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_myprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvancedJobSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_skills", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=50)),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("0-1", "0 to 1 years"),
                            ("1-2", "1 to 2 years"),
                            ("3-5", "3 to 5 years"),
                            ("5-10", "5 to 10 years"),
                        ],
                        max_length=5,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("industry", models.CharField(max_length=100)),
                ("function", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BoostnowProfileForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("education", models.TextField()),
                ("work_experience", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("certification", models.CharField(max_length=100)),
                ("completion_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ProfileHighlighter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("education", models.TextField()),
                ("work_experience", models.TextField()),
            ],
        ),
    ]
